# Generated by Django 2.2.2 on 2019-07-18 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=15)),
                ('zone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('Name', models.CharField(max_length=15, verbose_name='Full Name')),
                ('Contact', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('FarmName', models.CharField(max_length=20, verbose_name='Farm Name')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelativeWaterNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=40)),
                ('relativity_value', models.IntegerField()),
                ('sign', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StandardGrassDailyWaterNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_MDT', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_MDT', models.DecimalField(decimal_places=1, max_digits=5)),
                ('min_water', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_water', models.DecimalField(decimal_places=1, max_digits=5)),
                ('climatic_zone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TotalGrowingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=40)),
                ('min_growth_period', models.IntegerField()),
                ('max_growth_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterNeedRecommenderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climatic_zone', models.CharField(max_length=60)),
                ('crop', models.CharField(max_length=60)),
                ('sow_time', models.DateField()),
                ('farm', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='SetpointSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_sys_setpoint', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('farm', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('acknowledge', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('farm', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('farm', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='farm',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FARM_API.Farm'),
        ),
    ]
