# Generated by Django 2.2.2 on 2019-07-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARM_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
