# Generated by Django 2.2.2 on 2019-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARM_API', '0002_auto_20190719_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='status',
            field=models.CharField(default='..', max_length=20),
        ),
    ]
