# Generated by Django 2.2.2 on 2019-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARM_API', '0003_devicedata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterneedrecommenderinfo',
            name='daily_water',
            field=models.CharField(default='-', max_length=60),
        ),
    ]
