# Generated by Django 2.2.2 on 2019-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARM_API', '0004_waterneedrecommenderinfo_daily_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterneedrecommenderinfo',
            name='daily_water',
        ),
        migrations.AddField(
            model_name='waterneedrecommenderinfo',
            name='max_daily_water',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='waterneedrecommenderinfo',
            name='min_daily_water',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
