# Generated by Django 2.2.2 on 2019-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARM_API', '0006_auto_20190719_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterneedrecommenderinfo',
            name='climatic_zone',
        ),
        migrations.AddField(
            model_name='farm',
            name='climatic_zone',
            field=models.CharField(default='', max_length=60),
        ),
    ]
